/*
 * File:           EscritoresXMLHandler.java
 * Date:           October 26, 2015  12:47 PM
 *
 * @author  rodrigo
 * @version generated by NetBeans XML module
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica6;

import org.xml.sax.AttributeList;
import org.xml.sax.SAXException;

/**
 *
 * @author rodrigo
 */
public interface EscritoresXMLHandler {

    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     * @throws org.xml.sax.SAXException
     */
    public void start_escritor(final AttributeList meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     * @throws org.xml.sax.SAXException
     */
    public void end_escritor() throws SAXException;

    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_escritores(final AttributeList meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     * @throws org.xml.sax.SAXException
     */
    public void end_escritores() throws SAXException;

    /**
     *
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes
     * @throws org.xml.sax.SAXException
     */
    public void handle_nombre(final String data, final AttributeList meta) throws SAXException;

    /**
     *
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes
     * @throws org.xml.sax.SAXException
     */
    public void handle_nacimiento(final String data, final AttributeList meta) throws SAXException;
    
}
