/*
 * File:           EscritoresXMLHandlerImpl.java
 * Date:           October 26, 2015  12:47 PM
 *
 * @author  rodrigo
 * @version generated by NetBeans XML module
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica6;

import org.xml.sax.AttributeList;
import org.xml.sax.SAXException;

/**
 *
 * @author rodrigo
 */
public class EscritoresXMLHandlerImpl implements EscritoresXMLHandler {
    public static final boolean DEBUG = false;

    @Override
    public void start_escritor(final AttributeList meta) throws SAXException {
        if (DEBUG) {
            System.err.println("start_escritor: " + meta);
        }
    }

    @Override
    public void end_escritor() throws SAXException {
        if (DEBUG) {
            System.err.println("end_escritor()");
        }
    }

    @Override
    public void start_escritores(final AttributeList meta) throws SAXException {
        if (DEBUG) {
            System.err.println("start_escritores: " + meta);
        }
    }

    @Override
    public void end_escritores() throws SAXException {
        if (DEBUG) {
            System.err.println("end_escritores()");
        }
    }

    public void handle_nombre(final String data, final AttributeList meta) throws SAXException {
        if (DEBUG) {
            System.err.println("handle_nombre: " + meta);
        }
    }

    public void handle_nacimiento(final String data, final AttributeList meta) throws SAXException {
        if (DEBUG) {
            System.err.println("handle_nacimiento: " + meta);
        }
    }
    
}
